var namespace_supinfo_1_1_project_1_1_scripts_1_1_scriptable_objects_1_1_unit_types =
[
    [ "UnitType", "class_supinfo_1_1_project_1_1_scripts_1_1_scriptable_objects_1_1_unit_types_1_1_unit_type.html", "class_supinfo_1_1_project_1_1_scripts_1_1_scriptable_objects_1_1_unit_types_1_1_unit_type" ]
];