var namespace_supinfo_1_1_project_1_1_scripts_1_1_interfaces_1_1_upgrades =
[
    [ "IUpgradable", "interface_supinfo_1_1_project_1_1_scripts_1_1_interfaces_1_1_upgrades_1_1_i_upgradable.html", "interface_supinfo_1_1_project_1_1_scripts_1_1_interfaces_1_1_upgrades_1_1_i_upgradable" ]
];