// Attack STRATEGIE 

// BUY 0 TURRET 
// EVOLV MORE SPEEDLY IN AGE 

// ALWAYS PUT MELEE UNIT 
// WHEN PLAYER PLACE RESPOND AND PLACE UNIT RANDOMLY

// WHEN THERE +10 UNIT ON FIELD USE CAPACITY 

// CAPACITY : BUY GOLD AMELIORATION, UNIT armor / Range amelioration 

