// Defense STRATEGIE 

// BUY MAX TURRET 
// EVOLV MORE SPEEDLY IN AGE 

// NEVER PUT SOLO UNIT FOR ATTACK  / ALWAYS REPONSE TO PLAYER ATTACK
// ALWAY KEEP MONEY FOR BUYING ARMOR UNIT 
// WHEN PLAYER PLACE UNIT PLACE ARMOR / RANGE 

// WHEN THERE +5 UNIT ON FIELD USE CAPACITY 

// CAPACITY : BUY GOLD AMELIORATION, TURRET, ARMOR AND RANGE AMELLIORATION 

